autoload:
  sfPhpFit:
    name: sfPHPFit plugin libs
    path: %SF_PLUGINS_DIR%/sfPHPFitPlugin/lib
  sfPhpFit_proc:
    name: PHPFit fit proc
    path: %SF_PLUGINS_DIR%/sfPHPFitPlugin/lib/proc    
  sfPhpFit_reader:
    name: PHPFit fit reader
    path: %SF_PLUGINS_DIR%/sfPHPFitPlugin/lib/reader
  sfPhpFit_wikis:
    name: wikis
    path: %SF_PLUGINS_DIR%/sfPHPFitPlugin/lib/wiki
  sfPhpFit_phpfit:
    name: PHPFIT core files
    path: %SF_PLUGINS_DIR%/sfPHPFitPlugin/lib/vendor/phpfit
    exclude:
      - doc
      - eg
      - examples
      - tests
      - tools
  sfPhpFit_syntax_wiki:
    name: HatenaSyntx(wiki syntax)
    path: %SF_PLUGINS_DIR%/sfPHPFitPlugin/lib/vendor/HatenaSyntax
